# Site
name: "thoughtful works"
title: "thoughtful works"
description: "The primary objective of '<b>{{ site.name }}</b>' is to bring together a vibrant community of full-stack developers who possess a wide range of skills and expertise and to facilitate the free exchange of ideas and knowledge through virtual collaboration."
logo: "assets/images/logo/logo_transparent.png"
favicon: "assets/images/logo/logo_square.png"
baseurl: ""
disqus: 'thoughtfulworks'
mailchimp-list: ''
include: ["_pages"]
permalink: /:categories/:year/:title
email: hello@thoughtfulworks.dev
contact-us: https://formspree.io/f/mdoqkzjn
author: https://www.gravatar.com/avatar/6fc127cda8cd99830932538a58dc6173?s=250&d=mm&r=x

# Authors
authors:
  senthil:
    name: "Senthil Nayagan"
    display_name: "Senthil Nayagan"
    gravatar: 6fc127cda8cd99830932538a58dc6173
    email: "hello@senthilnayagan.com"
    web: https://senthilnayagan.com/
    linkedin: https://www.linkedin.com/in/senthilnayagan
    twitter: https://twitter.com/SenthilNayagan
    mastodon: https://fosstodon.org/@towardsdata
    instagram: https://www.instagram.com/senthilnayagan
    description: "I am a Data Engineer by profession and a Rustacean by interest. Lead Author and Content Creator: <a href='https://towardsdata.dev' target='_blank'>towardsdata.dev</a>, <a href='https://thoughtfulworks.dev' target='_blank'>thoughtfulworks.dev</a>, and <a href='https://rustinaction.dev' target='_blank'>rustinaction.dev</a>."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  #- flatify
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]